source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'PGBooks' do
    pod 'AFNetworking'
    pod 'PGTransitionKit' , '0.1.6'
end
